import {
  ArrowLeftIcon,
  ArrowRightIcon,
  BrowseIcon,
  BrowseOffIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  CloseCircleIcon,
  DashboardIcon,
  EllipsisIcon,
  ErrorCircleIcon,
  HelpCircleIcon,
  HomeIcon,
  LockOnIcon,
  LogoGithubIcon,
  MailIcon,
  MobileIcon,
  PoweroffIcon,
  PreciseMonitorIcon,
  RefreshIcon,
  SearchIcon,
  SettingIcon,
  UserCircleIcon,
  UserIcon,
  ViewListIcon,
} from 'tdesign-icons-vue-next';
import type { Component } from 'vue';

export const LOCAL_ICONS: Record<string, Component> = {
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  browse: BrowseIcon,
  'browse-off': BrowseOffIcon,
  'check-circle': CheckCircleIcon,
  'chevron-down': ChevronDownIcon,
  'close-circle': CloseCircleIcon,
  dashboard: DashboardIcon,
  ellipsis: EllipsisIcon,
  'error-circle': ErrorCircleIcon,
  'help-circle': HelpCircleIcon,
  home: HomeIcon,
  'lock-on': LockOnIcon,
  'logo-github': LogoGithubIcon,
  mail: MailIcon,
  mobile: MobileIcon,
  poweroff: PoweroffIcon,
  'precise-monitor': PreciseMonitorIcon,
  refresh: RefreshIcon,
  search: SearchIcon,
  setting: SettingIcon,
  user: UserIcon,
  'user-circle': UserCircleIcon,
  'view-list': ViewListIcon,
};
