import type { SiteConfig } from '@/types/status';

export const DEFAULT_SITE_CONFIG: SiteConfig = {
  version: 1,
  publicationStatus: 'published',
  siteName: '腾讯服务状态',
  timezone: 'Asia/Shanghai',
  dateFormat: 'YYYY-MM-DD HH:mm',
  themeColor: '#0052d9',
  sectionOrder: ['maintenances', 'components', 'incidents', 'history'],
  sectionVisibility: {
    maintenances: true,
    components: true,
    incidents: true,
    history: true,
  },
  maintenancePreviewLimit: 5,
  historyPreviewLimit: 5,
  text: {
    siteName: '腾讯服务状态',
    headerTitle: '服务状态',
    navCurrent: '当前状态',
    navHistory: '历史',
    overallTitles: {
      up: '所有服务正常',
      degraded: '部分服务性能下降',
      maintenance: '部分服务维护中',
      down: '部分服务异常',
    },
    overallMessages: {
      up: 'All Systems Operational',
      degraded: 'Degraded Performance',
      maintenance: 'Partial Maintenance',
      down: 'Partial System Outage',
    },
    maintenanceTitle: '计划与进行中的维护',
    componentTitle: '组件状态',
    componentSubtitle: '通栏为近 24 小时探测；双列半宽为近 30 日状态。',
    incidentTitle: '进行中的事件',
    historyTitle: '事件与维护历史',
    historySubtitle: '按开始时间倒序。完整进展请打开详情。',
    historyMoreHint: '更多事件请点击右上角查看',
    emptyMaintenance: '当前没有计划或进行中的维护',
    emptyIncident: '当前没有进行中的事件',
    footerText: '腾讯服务状态',
    adminFooterText: `Copyright © 2021-${new Date().getFullYear()} Tencent. All Rights Reserved`,
  },
  updatedAt: 0,
  publishedAt: 0,
};
